id: "nyt"
name: "The New York Times"
source_type_priority: ["rss", "html"]  # api slot later
frontpage_url: "https://www.nytimes.com/"
rss_feeds:
  - "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
max_items: 15
requires_js_render: false
respect_robots: true
throttle:
  per_host_rps: 1
headers:
  User-Agent: "CharliesEditorialBot/0.1 (contact: you@example.com)"


